{
    "id": "1f4e53b3-0846-4b48-aaa6-c2052c1c17d7",
    "timestamp": "2024-12-03T19:56:50.467753",
    "type": ".txt",
    "host_path": "/storage/sarthak.txt",
    "status": "scanned",
    "av_results": {
        "clamav": {
            "status": "error",
            "details": "('Connection aborted.', BadStatusLine('UNKNOWN COMMAND\\n'))"
        },
        "escan": {
            "status": "error",
            "details": "HTTPConnectionPool(host='localhost', port=3993): Max retries exceeded with url: /scan (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbd84b2e9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
        }
    }
}